project_name: ansisvg

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64  # 仅构建 amd64
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser

checksum:
  name_template: "checksums.txt"

archives:
  - files:
      - none*
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
